name: tizzy_watch
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^15.1.2
  lucide_icons: ^0.257.0
  android_intent_plus: ^5.3.0
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  flutter_launcher_icons: ^0.14.3
  freezed_annotation: ^3.1.0
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  json_annotation: ^4.9.0
  home_widget: ^0.8.0
  share_plus: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
